spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/activity_fitness
      database: activity_fitness
server:
  port: 8082

#mongodb://localhost:27017/