spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/activity_fitness
      database: activity_fitness
  rabbitmq:
    host: localhost
    port:  5672
    username: guest
    password: guest
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
